FROM golang:1.24-alpine

WORKDIR /app

# 安裝 Air
RUN go install github.com/air-verse/air@v1.61.7

# 複製 go.mod 與 go.sum 並下載依賴
COPY . .
RUN go mod download

# 這裡不 COPY 原始碼，因為我們會透過 Docker Compose 的 volumes 掛載進來
# 這樣你在本機改 code，容器內才會同步更新

# 啟動 Air
CMD ["air", "-c", ".air.mcp.toml"]