// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/mark3labs/mcp-go/server"
	"seanAIgent/internal/booking/domain/service"
	"seanAIgent/internal/booking/infra/db"
	"seanAIgent/internal/booking/transport/mcp"
	"seanAIgent/internal/booking/transport/mcp/tool"
	"seanAIgent/internal/booking/transport/web"
	"seanAIgent/internal/booking/transport/web/handler"
	"seanAIgent/internal/booking/usecase"
)

import (
	_ "github.com/94peter/vulpes/ezapi/session"
)

// Injectors from wire.go:

func InitializeWeb() web.WebService {
	dbRepository := db.NewDbRepoAndIdGenerate()
	trainDateService := service.NewTrainDateService(dbRepository)
	serviceAggregator := usecase.ServiceAggregator{
		TrainDateService: trainDateService,
	}
	writeUseCase := usecase.ProvideCreateTrainDateUC(dbRepository, serviceAggregator)
	coreWriteUseCase := usecase.ProvideBatchCreateTrainDateUC(dbRepository, serviceAggregator)
	writeUseCase2 := usecase.ProvideDeleteTrainDateUC(dbRepository)
	readUseCase := usecase.ProvideQueryFutureTrainUC(dbRepository)
	coreReadUseCase := usecase.ProvideFindNearestTrainByTimeUC(dbRepository)
	readUseCase2 := usecase.ProvideFindTrainHasApptsByIdUC(dbRepository)
	readUseCase3 := usecase.ProvideUserQueryFutureTrainUC(dbRepository)
	readUseCase4 := usecase.ProvideUserQueryTrainByIDUC(dbRepository)
	readUseCase5 := usecase.ProvideAdminQueryTrainRangeUC(dbRepository)
	readUseCase6 := usecase.ProvideAdminQueryRecentTrainUC(dbRepository)
	cacheWorker := usecase.NewCacheWorker(dbRepository)
	createApptUseCase := usecase.ProvideCreateApptUC(dbRepository, cacheWorker)
	adminCheckInUseCase := usecase.ProvideAdminCheckInUC(dbRepository, cacheWorker)
	checkInUseCase := usecase.ProvideCheckInUC(adminCheckInUseCase)
	cancelApptUseCase := usecase.ProvideCancelApptUC(dbRepository, cacheWorker)
	createLeaveUseCase := usecase.ProvideCreateLeaveUC(dbRepository, cacheWorker)
	cancelLeaveUseCase := usecase.ProvideCancelLeaveUC(dbRepository, cacheWorker)
	adminToggleCheckInUseCase := usecase.ProvideAdminToggleCheckInUC(dbRepository, cacheWorker)
	adminCreateLeaveUseCase := usecase.ProvideAdminCreateLeaveUC(dbRepository, cacheWorker)
	adminRestoreFromLeaveUseCase := usecase.ProvideAdminRestoreFromLeaveUC(dbRepository, cacheWorker)
	adminCreateWalkInUseCase := usecase.ProvideAdminCreateWalkInUC(dbRepository, cacheWorker)
	adminQueryStudentsUseCase := usecase.ProvideAdminQueryStudentsUC(dbRepository)
	autoMarkAbsentUseCase := usecase.ProvideAutoMarkAbsentUC(dbRepository)
	readUseCase7 := usecase.ProvideQueryUserBookingsUC(dbRepository)
	getUserMonthlyStatsUseCase := usecase.ProvideGetUserMonthlyStatsUC(dbRepository)
	queryTwoWeeksScheduleUseCase := usecase.ProvideQueryTwoWeeksScheduleUC(dbRepository)
	readUseCase8 := usecase.ProvideQueryAllUserApptStatsUC(dbRepository)
	idempotencyManager := usecase.ProvideIdempotencyManager()
	registry := &usecase.Registry{
		CreateTrainDate:        writeUseCase,
		BatchCreateTrainDate:   coreWriteUseCase,
		DeleteTrainDate:        writeUseCase2,
		QueryFutureTrain:       readUseCase,
		FindNearestTrainByTime: coreReadUseCase,
		FindTrainHasApptsById:  readUseCase2,
		UserQueryFutureTrain:   readUseCase3,
		UserQueryTrainByID:     readUseCase4,
		AdminQueryTrainRange:   readUseCase5,
		AdminQueryRecentTrain:  readUseCase6,
		CreateAppt:             createApptUseCase,
		CheckIn:                checkInUseCase,
		CancelAppt:             cancelApptUseCase,
		CreateLeave:            createLeaveUseCase,
		CancelLeave:            cancelLeaveUseCase,
		AdminCheckIn:           adminCheckInUseCase,
		AdminToggleCheckIn:     adminToggleCheckInUseCase,
		AdminCreateLeave:       adminCreateLeaveUseCase,
		AdminRestoreFromLeave:  adminRestoreFromLeaveUseCase,
		AdminCreateWalkIn:      adminCreateWalkInUseCase,
		AdminQueryStudents:     adminQueryStudentsUseCase,
		AutoMarkAbsent:         autoMarkAbsentUseCase,
		QueryUserBookings:      readUseCase7,
		GetUserMonthlyStats:    getUserMonthlyStatsUseCase,
		QueryTwoWeeksSchedule:  queryTwoWeeksScheduleUseCase,
		QueryAllUserApptStats:  readUseCase8,
		CacheWorker:            cacheWorker,
		IdempotencyManager:     idempotencyManager,
	}
	bookingUseCaseSet := handler.NewBookingUseCaseSet(registry)
	trainingUseCaseSet := handler.NewTrainingUseCaseSet(registry)
	v2BookingUseCaseSet := handler.NewV2BookingUseCaseSet(registry)
	config := ProvideWebConfig()
	webService := web.InitWeb(bookingUseCaseSet, trainingUseCaseSet, v2BookingUseCaseSet, registry, config)
	return webService
}

func InitializeMCP() mcp.Server {
	dbRepository := db.NewDbRepoAndIdGenerate()
	trainDateService := service.NewTrainDateService(dbRepository)
	serviceAggregator := usecase.ServiceAggregator{
		TrainDateService: trainDateService,
	}
	writeUseCase := usecase.ProvideCreateTrainDateUC(dbRepository, serviceAggregator)
	coreWriteUseCase := usecase.ProvideBatchCreateTrainDateUC(dbRepository, serviceAggregator)
	writeUseCase2 := usecase.ProvideDeleteTrainDateUC(dbRepository)
	readUseCase := usecase.ProvideQueryFutureTrainUC(dbRepository)
	coreReadUseCase := usecase.ProvideFindNearestTrainByTimeUC(dbRepository)
	readUseCase2 := usecase.ProvideFindTrainHasApptsByIdUC(dbRepository)
	readUseCase3 := usecase.ProvideUserQueryFutureTrainUC(dbRepository)
	readUseCase4 := usecase.ProvideUserQueryTrainByIDUC(dbRepository)
	readUseCase5 := usecase.ProvideAdminQueryTrainRangeUC(dbRepository)
	readUseCase6 := usecase.ProvideAdminQueryRecentTrainUC(dbRepository)
	cacheWorker := usecase.NewCacheWorker(dbRepository)
	createApptUseCase := usecase.ProvideCreateApptUC(dbRepository, cacheWorker)
	adminCheckInUseCase := usecase.ProvideAdminCheckInUC(dbRepository, cacheWorker)
	checkInUseCase := usecase.ProvideCheckInUC(adminCheckInUseCase)
	cancelApptUseCase := usecase.ProvideCancelApptUC(dbRepository, cacheWorker)
	createLeaveUseCase := usecase.ProvideCreateLeaveUC(dbRepository, cacheWorker)
	cancelLeaveUseCase := usecase.ProvideCancelLeaveUC(dbRepository, cacheWorker)
	adminToggleCheckInUseCase := usecase.ProvideAdminToggleCheckInUC(dbRepository, cacheWorker)
	adminCreateLeaveUseCase := usecase.ProvideAdminCreateLeaveUC(dbRepository, cacheWorker)
	adminRestoreFromLeaveUseCase := usecase.ProvideAdminRestoreFromLeaveUC(dbRepository, cacheWorker)
	adminCreateWalkInUseCase := usecase.ProvideAdminCreateWalkInUC(dbRepository, cacheWorker)
	adminQueryStudentsUseCase := usecase.ProvideAdminQueryStudentsUC(dbRepository)
	autoMarkAbsentUseCase := usecase.ProvideAutoMarkAbsentUC(dbRepository)
	readUseCase7 := usecase.ProvideQueryUserBookingsUC(dbRepository)
	getUserMonthlyStatsUseCase := usecase.ProvideGetUserMonthlyStatsUC(dbRepository)
	queryTwoWeeksScheduleUseCase := usecase.ProvideQueryTwoWeeksScheduleUC(dbRepository)
	readUseCase8 := usecase.ProvideQueryAllUserApptStatsUC(dbRepository)
	idempotencyManager := usecase.ProvideIdempotencyManager()
	registry := &usecase.Registry{
		CreateTrainDate:        writeUseCase,
		BatchCreateTrainDate:   coreWriteUseCase,
		DeleteTrainDate:        writeUseCase2,
		QueryFutureTrain:       readUseCase,
		FindNearestTrainByTime: coreReadUseCase,
		FindTrainHasApptsById:  readUseCase2,
		UserQueryFutureTrain:   readUseCase3,
		UserQueryTrainByID:     readUseCase4,
		AdminQueryTrainRange:   readUseCase5,
		AdminQueryRecentTrain:  readUseCase6,
		CreateAppt:             createApptUseCase,
		CheckIn:                checkInUseCase,
		CancelAppt:             cancelApptUseCase,
		CreateLeave:            createLeaveUseCase,
		CancelLeave:            cancelLeaveUseCase,
		AdminCheckIn:           adminCheckInUseCase,
		AdminToggleCheckIn:     adminToggleCheckInUseCase,
		AdminCreateLeave:       adminCreateLeaveUseCase,
		AdminRestoreFromLeave:  adminRestoreFromLeaveUseCase,
		AdminCreateWalkIn:      adminCreateWalkInUseCase,
		AdminQueryStudents:     adminQueryStudentsUseCase,
		AutoMarkAbsent:         autoMarkAbsentUseCase,
		QueryUserBookings:      readUseCase7,
		GetUserMonthlyStats:    getUserMonthlyStatsUseCase,
		QueryTwoWeeksSchedule:  queryTwoWeeksScheduleUseCase,
		QueryAllUserApptStats:  readUseCase8,
		CacheWorker:            cacheWorker,
		IdempotencyManager:     idempotencyManager,
	}
	v := toolSet()
	server := mcp.InitMcpServer(registry, v)
	return server
}

func GetUseCaseRegistry() *usecase.Registry {
	dbRepository := db.NewDbRepoAndIdGenerate()
	trainDateService := service.NewTrainDateService(dbRepository)
	serviceAggregator := usecase.ServiceAggregator{
		TrainDateService: trainDateService,
	}
	writeUseCase := usecase.ProvideCreateTrainDateUC(dbRepository, serviceAggregator)
	coreWriteUseCase := usecase.ProvideBatchCreateTrainDateUC(dbRepository, serviceAggregator)
	writeUseCase2 := usecase.ProvideDeleteTrainDateUC(dbRepository)
	readUseCase := usecase.ProvideQueryFutureTrainUC(dbRepository)
	coreReadUseCase := usecase.ProvideFindNearestTrainByTimeUC(dbRepository)
	readUseCase2 := usecase.ProvideFindTrainHasApptsByIdUC(dbRepository)
	readUseCase3 := usecase.ProvideUserQueryFutureTrainUC(dbRepository)
	readUseCase4 := usecase.ProvideUserQueryTrainByIDUC(dbRepository)
	readUseCase5 := usecase.ProvideAdminQueryTrainRangeUC(dbRepository)
	readUseCase6 := usecase.ProvideAdminQueryRecentTrainUC(dbRepository)
	cacheWorker := usecase.NewCacheWorker(dbRepository)
	createApptUseCase := usecase.ProvideCreateApptUC(dbRepository, cacheWorker)
	adminCheckInUseCase := usecase.ProvideAdminCheckInUC(dbRepository, cacheWorker)
	checkInUseCase := usecase.ProvideCheckInUC(adminCheckInUseCase)
	cancelApptUseCase := usecase.ProvideCancelApptUC(dbRepository, cacheWorker)
	createLeaveUseCase := usecase.ProvideCreateLeaveUC(dbRepository, cacheWorker)
	cancelLeaveUseCase := usecase.ProvideCancelLeaveUC(dbRepository, cacheWorker)
	adminToggleCheckInUseCase := usecase.ProvideAdminToggleCheckInUC(dbRepository, cacheWorker)
	adminCreateLeaveUseCase := usecase.ProvideAdminCreateLeaveUC(dbRepository, cacheWorker)
	adminRestoreFromLeaveUseCase := usecase.ProvideAdminRestoreFromLeaveUC(dbRepository, cacheWorker)
	adminCreateWalkInUseCase := usecase.ProvideAdminCreateWalkInUC(dbRepository, cacheWorker)
	adminQueryStudentsUseCase := usecase.ProvideAdminQueryStudentsUC(dbRepository)
	autoMarkAbsentUseCase := usecase.ProvideAutoMarkAbsentUC(dbRepository)
	readUseCase7 := usecase.ProvideQueryUserBookingsUC(dbRepository)
	getUserMonthlyStatsUseCase := usecase.ProvideGetUserMonthlyStatsUC(dbRepository)
	queryTwoWeeksScheduleUseCase := usecase.ProvideQueryTwoWeeksScheduleUC(dbRepository)
	readUseCase8 := usecase.ProvideQueryAllUserApptStatsUC(dbRepository)
	idempotencyManager := usecase.ProvideIdempotencyManager()
	registry := &usecase.Registry{
		CreateTrainDate:        writeUseCase,
		BatchCreateTrainDate:   coreWriteUseCase,
		DeleteTrainDate:        writeUseCase2,
		QueryFutureTrain:       readUseCase,
		FindNearestTrainByTime: coreReadUseCase,
		FindTrainHasApptsById:  readUseCase2,
		UserQueryFutureTrain:   readUseCase3,
		UserQueryTrainByID:     readUseCase4,
		AdminQueryTrainRange:   readUseCase5,
		AdminQueryRecentTrain:  readUseCase6,
		CreateAppt:             createApptUseCase,
		CheckIn:                checkInUseCase,
		CancelAppt:             cancelApptUseCase,
		CreateLeave:            createLeaveUseCase,
		CancelLeave:            cancelLeaveUseCase,
		AdminCheckIn:           adminCheckInUseCase,
		AdminToggleCheckIn:     adminToggleCheckInUseCase,
		AdminCreateLeave:       adminCreateLeaveUseCase,
		AdminRestoreFromLeave:  adminRestoreFromLeaveUseCase,
		AdminCreateWalkIn:      adminCreateWalkInUseCase,
		AdminQueryStudents:     adminQueryStudentsUseCase,
		AutoMarkAbsent:         autoMarkAbsentUseCase,
		QueryUserBookings:      readUseCase7,
		GetUserMonthlyStats:    getUserMonthlyStatsUseCase,
		QueryTwoWeeksSchedule:  queryTwoWeeksScheduleUseCase,
		QueryAllUserApptStats:  readUseCase8,
		CacheWorker:            cacheWorker,
		IdempotencyManager:     idempotencyManager,
	}
	return registry
}

// wire.go:

func toolSet() []server.ServerTool {
	return []server.ServerTool{tool.ProvideCreateTrainingCoursesTool(), tool.ProvideDeleteLeaveByIdTool(), tool.ProvideQueryLeaveByDateTool(), tool.ProvideQueryTrainingByRangeTool()}
}
