// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"seanAIgent/internal/booking/domain/service"
	"seanAIgent/internal/booking/infra/db"
	"seanAIgent/internal/booking/transport/web"
	"seanAIgent/internal/booking/transport/web/handler"
	"seanAIgent/internal/booking/usecase"
)

import (
	_ "github.com/94peter/vulpes/ezapi/session"
	_ "seanAIgent/internal/mcp/tool"
)

// Injectors from wire.go:

func InitializeWeb() web.WebService {
	dbRepository := db.NewDbRepoAndIdGenerate()
	trainDateService := service.NewTrainDateService(dbRepository)
	serviceAggregator := usecase.ServiceAggregator{
		TrainDateService: trainDateService,
	}
	writeUseCase := usecase.ProvideCreateTrainDateUC(dbRepository, serviceAggregator)
	coreWriteUseCase := usecase.ProvideBatchCreateTrainDateUC(dbRepository, serviceAggregator)
	writeUseCase2 := usecase.ProvideDeleteTrainDateUC(dbRepository)
	readUseCase := usecase.ProvideQueryFutureTrainUC(dbRepository)
	coreReadUseCase := usecase.ProvideFindNearestTrainByTimeUC(dbRepository)
	readUseCase2 := usecase.ProvideUserQueryFutureTrainUC(dbRepository)
	readUseCase3 := usecase.ProvideUserQueryTrainByIDUC(dbRepository)
	writeUseCase3 := usecase.ProvideCreateApptUC(dbRepository)
	writeUseCase4 := usecase.ProvideCheckInUC(dbRepository)
	writeUseCase5 := usecase.ProvideCancelApptUC(dbRepository)
	writeUseCase6 := usecase.ProvideCreateLeaveUC(dbRepository)
	writeUseCase7 := usecase.ProvideCancelLeaveUC(dbRepository)
	readUseCase4 := usecase.ProvideQueryUserBookingsUC(dbRepository)
	registry := &usecase.Registry{
		CreateTrainDate:        writeUseCase,
		BatchCreateTrainDate:   coreWriteUseCase,
		DeleteTrainDate:        writeUseCase2,
		QueryFutureTrain:       readUseCase,
		FindNearestTrainByTime: coreReadUseCase,
		UserQueryFutureTrain:   readUseCase2,
		UserQueryTrainByID:     readUseCase3,
		CreateAppt:             writeUseCase3,
		CheckIn:                writeUseCase4,
		CancelAppt:             writeUseCase5,
		CreateLeave:            writeUseCase6,
		CancelLeave:            writeUseCase7,
		QueryUserBookings:      readUseCase4,
	}
	bookingUseCaseSet := handler.NewBookingUseCaseSet(registry)
	trainingUseCaseSet := handler.NewTrainingUseCaseSet(registry)
	config := ProvideWebConfig()
	webService := web.InitWeb(bookingUseCaseSet, trainingUseCaseSet, config)
	return webService
}
