// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/94peter/vulpes/db/mgo"
	"github.com/mark3labs/mcp-go/server"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"seanAIgent/internal/booking/domain/service"
	"seanAIgent/internal/booking/infra/db"
	"seanAIgent/internal/booking/transport/mcp"
	"seanAIgent/internal/booking/transport/mcp/tool"
	"seanAIgent/internal/booking/transport/web"
	"seanAIgent/internal/booking/transport/web/handler"
	"seanAIgent/internal/booking/usecase"
	"seanAIgent/internal/event"
)

import (
	_ "github.com/94peter/vulpes/ezapi/session"
)

// Injectors from wire.go:

func InitializeWeb() (web.WebService, error) {
	dbRepository := db.NewDbRepoAndIdGenerate()
	trainDateService := service.NewTrainDateService(dbRepository)
	serviceAggregator := usecase.ServiceAggregator{
		TrainDateService: trainDateService,
	}
	writeUseCase := usecase.ProvideCreateTrainDateUC(dbRepository, serviceAggregator)
	coreWriteUseCase := usecase.ProvideBatchCreateTrainDateUC(dbRepository, serviceAggregator)
	writeUseCase2 := usecase.ProvideDeleteTrainDateUC(dbRepository)
	readUseCase := usecase.ProvideQueryFutureTrainUC(dbRepository)
	coreReadUseCase := usecase.ProvideFindNearestTrainByTimeUC(dbRepository)
	readUseCase2 := usecase.ProvideFindTrainHasApptsByIdUC(dbRepository)
	readUseCase3 := usecase.ProvideUserQueryFutureTrainUC(dbRepository)
	readUseCase4 := usecase.ProvideUserQueryTrainByIDUC(dbRepository)
	readUseCase5 := usecase.ProvideAdminQueryTrainRangeUC(dbRepository)
	readUseCase6 := usecase.ProvideAdminQueryRecentTrainUC(dbRepository)
	database := ProvideDatabase()
	eventStore, err := event.ProvideEventStore(database)
	if err != nil {
		return nil, err
	}
	bus := event.ProvideEventBus(eventStore)
	createApptUseCase := usecase.ProvideCreateApptUC(dbRepository, bus)
	adminCheckInUseCase := usecase.ProvideAdminCheckInUC(dbRepository, bus)
	checkInUseCase := usecase.ProvideCheckInUC(adminCheckInUseCase)
	cancelApptUseCase := usecase.ProvideCancelApptUC(dbRepository, bus)
	createLeaveUseCase := usecase.ProvideCreateLeaveUC(dbRepository, bus)
	cancelLeaveUseCase := usecase.ProvideCancelLeaveUC(dbRepository, bus)
	adminToggleCheckInUseCase := usecase.ProvideAdminToggleCheckInUC(dbRepository, bus)
	adminCreateLeaveUseCase := usecase.ProvideAdminCreateLeaveUC(dbRepository, bus)
	adminRestoreFromLeaveUseCase := usecase.ProvideAdminRestoreFromLeaveUC(dbRepository, bus)
	adminCreateWalkInUseCase := usecase.ProvideAdminCreateWalkInUC(dbRepository, bus)
	adminQueryStudentsUseCase := usecase.ProvideAdminQueryStudentsUC(dbRepository)
	autoMarkAbsentUseCase := usecase.ProvideAutoMarkAbsentUC(dbRepository, bus)
	adminBatchUpdateAttendanceUseCase := usecase.ProvideAdminBatchUpdateAttendanceUC(dbRepository, bus)
	readUseCase7 := usecase.ProvideQueryUserBookingsUC(dbRepository)
	getUserMonthlyStatsUseCase := usecase.ProvideGetUserMonthlyStatsUC(dbRepository)
	queryTwoWeeksScheduleUseCase := usecase.ProvideQueryTwoWeeksScheduleUC(dbRepository)
	readUseCase8 := usecase.ProvideQueryAllUserApptStatsUC(dbRepository)
	batchSyncMonthlyStatsUseCase := usecase.ProvideBatchSyncMonthlyStatsUC(dbRepository)
	queryMonthlyUserReportsUseCase := usecase.ProvideQueryMonthlyUserReportsUC(dbRepository)
	getBusinessAnalyticsUseCase := usecase.ProvideGetBusinessAnalyticsUC(dbRepository)
	getUserDetailUseCase := usecase.ProvideGetUserDetailUC(dbRepository)
	v := usecase.ProvideSubscribers(dbRepository)
	idempotencyManager := usecase.ProvideIdempotencyManager()
	registry := &usecase.Registry{
		CreateTrainDate:            writeUseCase,
		BatchCreateTrainDate:       coreWriteUseCase,
		DeleteTrainDate:            writeUseCase2,
		QueryFutureTrain:           readUseCase,
		FindNearestTrainByTime:     coreReadUseCase,
		FindTrainHasApptsById:      readUseCase2,
		UserQueryFutureTrain:       readUseCase3,
		UserQueryTrainByID:         readUseCase4,
		AdminQueryTrainRange:       readUseCase5,
		AdminQueryRecentTrain:      readUseCase6,
		CreateAppt:                 createApptUseCase,
		CheckIn:                    checkInUseCase,
		CancelAppt:                 cancelApptUseCase,
		CreateLeave:                createLeaveUseCase,
		CancelLeave:                cancelLeaveUseCase,
		AdminCheckIn:               adminCheckInUseCase,
		AdminToggleCheckIn:         adminToggleCheckInUseCase,
		AdminCreateLeave:           adminCreateLeaveUseCase,
		AdminRestoreFromLeave:      adminRestoreFromLeaveUseCase,
		AdminCreateWalkIn:          adminCreateWalkInUseCase,
		AdminQueryStudents:         adminQueryStudentsUseCase,
		AutoMarkAbsent:             autoMarkAbsentUseCase,
		AdminBatchUpdateAttendance: adminBatchUpdateAttendanceUseCase,
		QueryUserBookings:          readUseCase7,
		GetUserMonthlyStats:        getUserMonthlyStatsUseCase,
		QueryTwoWeeksSchedule:      queryTwoWeeksScheduleUseCase,
		QueryAllUserApptStats:      readUseCase8,
		BatchSyncMonthlyStats:      batchSyncMonthlyStatsUseCase,
		QueryMonthlyUserReports:    queryMonthlyUserReportsUseCase,
		GetBusinessAnalytics:       getBusinessAnalyticsUseCase,
		GetUserDetail:              getUserDetailUseCase,
		Bus:                        bus,
		Subscribers:                v,
		IdempotencyManager:         idempotencyManager,
	}
	bookingUseCaseSet := handler.NewBookingUseCaseSet(registry)
	trainingUseCaseSet := handler.NewTrainingUseCaseSet(registry)
	v2BookingUseCaseSet := handler.NewV2BookingUseCaseSet(registry)
	config := ProvideWebConfig()
	webService := web.InitWeb(bookingUseCaseSet, trainingUseCaseSet, v2BookingUseCaseSet, registry, config)
	return webService, nil
}

func InitializeMCP() (mcp.Server, error) {
	dbRepository := db.NewDbRepoAndIdGenerate()
	trainDateService := service.NewTrainDateService(dbRepository)
	serviceAggregator := usecase.ServiceAggregator{
		TrainDateService: trainDateService,
	}
	writeUseCase := usecase.ProvideCreateTrainDateUC(dbRepository, serviceAggregator)
	coreWriteUseCase := usecase.ProvideBatchCreateTrainDateUC(dbRepository, serviceAggregator)
	writeUseCase2 := usecase.ProvideDeleteTrainDateUC(dbRepository)
	readUseCase := usecase.ProvideQueryFutureTrainUC(dbRepository)
	coreReadUseCase := usecase.ProvideFindNearestTrainByTimeUC(dbRepository)
	readUseCase2 := usecase.ProvideFindTrainHasApptsByIdUC(dbRepository)
	readUseCase3 := usecase.ProvideUserQueryFutureTrainUC(dbRepository)
	readUseCase4 := usecase.ProvideUserQueryTrainByIDUC(dbRepository)
	readUseCase5 := usecase.ProvideAdminQueryTrainRangeUC(dbRepository)
	readUseCase6 := usecase.ProvideAdminQueryRecentTrainUC(dbRepository)
	database := ProvideDatabase()
	eventStore, err := event.ProvideEventStore(database)
	if err != nil {
		return nil, err
	}
	bus := event.ProvideEventBus(eventStore)
	createApptUseCase := usecase.ProvideCreateApptUC(dbRepository, bus)
	adminCheckInUseCase := usecase.ProvideAdminCheckInUC(dbRepository, bus)
	checkInUseCase := usecase.ProvideCheckInUC(adminCheckInUseCase)
	cancelApptUseCase := usecase.ProvideCancelApptUC(dbRepository, bus)
	createLeaveUseCase := usecase.ProvideCreateLeaveUC(dbRepository, bus)
	cancelLeaveUseCase := usecase.ProvideCancelLeaveUC(dbRepository, bus)
	adminToggleCheckInUseCase := usecase.ProvideAdminToggleCheckInUC(dbRepository, bus)
	adminCreateLeaveUseCase := usecase.ProvideAdminCreateLeaveUC(dbRepository, bus)
	adminRestoreFromLeaveUseCase := usecase.ProvideAdminRestoreFromLeaveUC(dbRepository, bus)
	adminCreateWalkInUseCase := usecase.ProvideAdminCreateWalkInUC(dbRepository, bus)
	adminQueryStudentsUseCase := usecase.ProvideAdminQueryStudentsUC(dbRepository)
	autoMarkAbsentUseCase := usecase.ProvideAutoMarkAbsentUC(dbRepository, bus)
	adminBatchUpdateAttendanceUseCase := usecase.ProvideAdminBatchUpdateAttendanceUC(dbRepository, bus)
	readUseCase7 := usecase.ProvideQueryUserBookingsUC(dbRepository)
	getUserMonthlyStatsUseCase := usecase.ProvideGetUserMonthlyStatsUC(dbRepository)
	queryTwoWeeksScheduleUseCase := usecase.ProvideQueryTwoWeeksScheduleUC(dbRepository)
	readUseCase8 := usecase.ProvideQueryAllUserApptStatsUC(dbRepository)
	batchSyncMonthlyStatsUseCase := usecase.ProvideBatchSyncMonthlyStatsUC(dbRepository)
	queryMonthlyUserReportsUseCase := usecase.ProvideQueryMonthlyUserReportsUC(dbRepository)
	getBusinessAnalyticsUseCase := usecase.ProvideGetBusinessAnalyticsUC(dbRepository)
	getUserDetailUseCase := usecase.ProvideGetUserDetailUC(dbRepository)
	v := usecase.ProvideSubscribers(dbRepository)
	idempotencyManager := usecase.ProvideIdempotencyManager()
	registry := &usecase.Registry{
		CreateTrainDate:            writeUseCase,
		BatchCreateTrainDate:       coreWriteUseCase,
		DeleteTrainDate:            writeUseCase2,
		QueryFutureTrain:           readUseCase,
		FindNearestTrainByTime:     coreReadUseCase,
		FindTrainHasApptsById:      readUseCase2,
		UserQueryFutureTrain:       readUseCase3,
		UserQueryTrainByID:         readUseCase4,
		AdminQueryTrainRange:       readUseCase5,
		AdminQueryRecentTrain:      readUseCase6,
		CreateAppt:                 createApptUseCase,
		CheckIn:                    checkInUseCase,
		CancelAppt:                 cancelApptUseCase,
		CreateLeave:                createLeaveUseCase,
		CancelLeave:                cancelLeaveUseCase,
		AdminCheckIn:               adminCheckInUseCase,
		AdminToggleCheckIn:         adminToggleCheckInUseCase,
		AdminCreateLeave:           adminCreateLeaveUseCase,
		AdminRestoreFromLeave:      adminRestoreFromLeaveUseCase,
		AdminCreateWalkIn:          adminCreateWalkInUseCase,
		AdminQueryStudents:         adminQueryStudentsUseCase,
		AutoMarkAbsent:             autoMarkAbsentUseCase,
		AdminBatchUpdateAttendance: adminBatchUpdateAttendanceUseCase,
		QueryUserBookings:          readUseCase7,
		GetUserMonthlyStats:        getUserMonthlyStatsUseCase,
		QueryTwoWeeksSchedule:      queryTwoWeeksScheduleUseCase,
		QueryAllUserApptStats:      readUseCase8,
		BatchSyncMonthlyStats:      batchSyncMonthlyStatsUseCase,
		QueryMonthlyUserReports:    queryMonthlyUserReportsUseCase,
		GetBusinessAnalytics:       getBusinessAnalyticsUseCase,
		GetUserDetail:              getUserDetailUseCase,
		Bus:                        bus,
		Subscribers:                v,
		IdempotencyManager:         idempotencyManager,
	}
	v2 := toolSet()
	server := mcp.InitMcpServer(registry, v2)
	return server, nil
}

func GetUseCaseRegistry() (*usecase.Registry, error) {
	dbRepository := db.NewDbRepoAndIdGenerate()
	trainDateService := service.NewTrainDateService(dbRepository)
	serviceAggregator := usecase.ServiceAggregator{
		TrainDateService: trainDateService,
	}
	writeUseCase := usecase.ProvideCreateTrainDateUC(dbRepository, serviceAggregator)
	coreWriteUseCase := usecase.ProvideBatchCreateTrainDateUC(dbRepository, serviceAggregator)
	writeUseCase2 := usecase.ProvideDeleteTrainDateUC(dbRepository)
	readUseCase := usecase.ProvideQueryFutureTrainUC(dbRepository)
	coreReadUseCase := usecase.ProvideFindNearestTrainByTimeUC(dbRepository)
	readUseCase2 := usecase.ProvideFindTrainHasApptsByIdUC(dbRepository)
	readUseCase3 := usecase.ProvideUserQueryFutureTrainUC(dbRepository)
	readUseCase4 := usecase.ProvideUserQueryTrainByIDUC(dbRepository)
	readUseCase5 := usecase.ProvideAdminQueryTrainRangeUC(dbRepository)
	readUseCase6 := usecase.ProvideAdminQueryRecentTrainUC(dbRepository)
	database := ProvideDatabase()
	eventStore, err := event.ProvideEventStore(database)
	if err != nil {
		return nil, err
	}
	bus := event.ProvideEventBus(eventStore)
	createApptUseCase := usecase.ProvideCreateApptUC(dbRepository, bus)
	adminCheckInUseCase := usecase.ProvideAdminCheckInUC(dbRepository, bus)
	checkInUseCase := usecase.ProvideCheckInUC(adminCheckInUseCase)
	cancelApptUseCase := usecase.ProvideCancelApptUC(dbRepository, bus)
	createLeaveUseCase := usecase.ProvideCreateLeaveUC(dbRepository, bus)
	cancelLeaveUseCase := usecase.ProvideCancelLeaveUC(dbRepository, bus)
	adminToggleCheckInUseCase := usecase.ProvideAdminToggleCheckInUC(dbRepository, bus)
	adminCreateLeaveUseCase := usecase.ProvideAdminCreateLeaveUC(dbRepository, bus)
	adminRestoreFromLeaveUseCase := usecase.ProvideAdminRestoreFromLeaveUC(dbRepository, bus)
	adminCreateWalkInUseCase := usecase.ProvideAdminCreateWalkInUC(dbRepository, bus)
	adminQueryStudentsUseCase := usecase.ProvideAdminQueryStudentsUC(dbRepository)
	autoMarkAbsentUseCase := usecase.ProvideAutoMarkAbsentUC(dbRepository, bus)
	adminBatchUpdateAttendanceUseCase := usecase.ProvideAdminBatchUpdateAttendanceUC(dbRepository, bus)
	readUseCase7 := usecase.ProvideQueryUserBookingsUC(dbRepository)
	getUserMonthlyStatsUseCase := usecase.ProvideGetUserMonthlyStatsUC(dbRepository)
	queryTwoWeeksScheduleUseCase := usecase.ProvideQueryTwoWeeksScheduleUC(dbRepository)
	readUseCase8 := usecase.ProvideQueryAllUserApptStatsUC(dbRepository)
	batchSyncMonthlyStatsUseCase := usecase.ProvideBatchSyncMonthlyStatsUC(dbRepository)
	queryMonthlyUserReportsUseCase := usecase.ProvideQueryMonthlyUserReportsUC(dbRepository)
	getBusinessAnalyticsUseCase := usecase.ProvideGetBusinessAnalyticsUC(dbRepository)
	getUserDetailUseCase := usecase.ProvideGetUserDetailUC(dbRepository)
	v := usecase.ProvideSubscribers(dbRepository)
	idempotencyManager := usecase.ProvideIdempotencyManager()
	registry := &usecase.Registry{
		CreateTrainDate:            writeUseCase,
		BatchCreateTrainDate:       coreWriteUseCase,
		DeleteTrainDate:            writeUseCase2,
		QueryFutureTrain:           readUseCase,
		FindNearestTrainByTime:     coreReadUseCase,
		FindTrainHasApptsById:      readUseCase2,
		UserQueryFutureTrain:       readUseCase3,
		UserQueryTrainByID:         readUseCase4,
		AdminQueryTrainRange:       readUseCase5,
		AdminQueryRecentTrain:      readUseCase6,
		CreateAppt:                 createApptUseCase,
		CheckIn:                    checkInUseCase,
		CancelAppt:                 cancelApptUseCase,
		CreateLeave:                createLeaveUseCase,
		CancelLeave:                cancelLeaveUseCase,
		AdminCheckIn:               adminCheckInUseCase,
		AdminToggleCheckIn:         adminToggleCheckInUseCase,
		AdminCreateLeave:           adminCreateLeaveUseCase,
		AdminRestoreFromLeave:      adminRestoreFromLeaveUseCase,
		AdminCreateWalkIn:          adminCreateWalkInUseCase,
		AdminQueryStudents:         adminQueryStudentsUseCase,
		AutoMarkAbsent:             autoMarkAbsentUseCase,
		AdminBatchUpdateAttendance: adminBatchUpdateAttendanceUseCase,
		QueryUserBookings:          readUseCase7,
		GetUserMonthlyStats:        getUserMonthlyStatsUseCase,
		QueryTwoWeeksSchedule:      queryTwoWeeksScheduleUseCase,
		QueryAllUserApptStats:      readUseCase8,
		BatchSyncMonthlyStats:      batchSyncMonthlyStatsUseCase,
		QueryMonthlyUserReports:    queryMonthlyUserReportsUseCase,
		GetBusinessAnalytics:       getBusinessAnalyticsUseCase,
		GetUserDetail:              getUserDetailUseCase,
		Bus:                        bus,
		Subscribers:                v,
		IdempotencyManager:         idempotencyManager,
	}
	return registry, nil
}

// wire.go:

func ProvideDatabase() *mongo.Database {
	return mgo.GetDatabase()
}

func toolSet() []server.ServerTool {
	return []server.ServerTool{tool.ProvideCreateTrainingCoursesTool(), tool.ProvideDeleteLeaveByIdTool(), tool.ProvideQueryLeaveByDateTool(), tool.ProvideQueryTrainingByRangeTool()}
}
